### ISSUE TITLE
Actor supervision strategy

### ISSUE THREAD

**Issue by dmitri-carpov** [ypg-data/eigenflow#21]
This issue is created to track a discussion of actor supervision strategy. When an actor fails in runtime there is no strategy defined how to handle those. It leads to a "hung" process.

copy/paste from a pr discussion:

---

 there may be scenarios where recovery doesn't complete (due to failures encountered etc). this leads to two questions which need to be dealt with in the context of #14 and would need to be resolved before this PR in it's current form can be merged (since it's merger will close #14). if needed, the commit could be reworded if we don't want to wait for the questions below before merging this PR (resolving questions will take time). the questions are:
- [ ] what are the scenarios (failure or otherwise) that would lead to onRecoveryCompleted does not fire
- [ ] how should we behave in such scenarios? should we still run the job from the date in question obeying the reset flag?
- [ ] updates to the code implementing any tweaks identified above

---

In my opinion, the strategy of dealing with actor failures has a wider scope than the current bugfix. Therefore, I suggest to open another issue to continue this discussion.

**Comment by sheenaluu** [comment]
Recent example of a failure causing the job to hang:  https://issues.ypg.com/browse/MPN-3057.
(Log snippet is attached to the ticket.)

**Comment by WadeWaldron** [comment]
Encountered this (or something like it) again today.  Kafka producer appears to have failed and the result was the job hung.  Because it didn't shutdown, none of the failure mechanisms were able to kick in and the job had to be manually restarted.

```
[WARN] [2016/05/04 20:56:21.002] [kafka-producer-network-thread | producer-1] [org.apache.kafka.common.network.Selector] Error in I/O with <some ip address>
java.io.EOFException: null
    at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:62) ~[testjob-20160504T213534.jar:20160504T213534]
    at org.apache.kafka.common.network.Selector.poll(Selector.java:248) ~[testjob-20160504T213534.jar:20160504T213534]
    at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:192) [testjob-20160504T213534.jar:20160504T213534]
    at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:191) [testjob-20160504T213534.jar:20160504T213534]
    at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:122) [testjob-20160504T213534.jar:20160504T213534]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]
```
